Repository ita-social-projects/ZeroWaste, pull requests merged in 2022-11, with the labels that each got.

#271 ZER-178 Fix declension of diaper when kid’s age is not chosen
  app/views/calculators/calculator.html.slim
Labels: enhancement

#273 ZER-145 Add UKR Localization for "Yes, I want to receive email messages"
  app/helpers/calculators_helper.rb
  config/locales/en.yml
  config/locales/uk.yml
Labels: enhancement

#269 chore(any_login) add gem any_login
  Gemfile
  Gemfile.lock
  app/models/user.rb
  app/views/layouts/application.html.slim
  config/initializers/any_login.rb
  db/schema.rb
  db/seeds.rb
  yarn.lock
Labels: enhancement

#275 ZER-184-Change-logo-and-button
  app/assets/images/logo_zerowaste.png
  app/javascript/css/calculator.css.scss
  app/views/layouts/_admin_navbar.html.slim
  app/views/layouts/_navigation.html.slim
Labels: bug

#278 fix automation tests for SignIn
  app/views/devise/registrations/new.html.slim
  config/locales/en.yml
  config/locales/uk.yml
  spec/features/sing_up_spec.rb
Labels: bug

#277 Delete 'Well done!' from console
  app/javascript/packs/application.js
Labels: enhancement

#272 ZER-180 fix defect of cross area in calculator
  app/assets/stylesheets/main.css.scss.erb
  app/javascript/css/calculator.css.scss
  app/javascript/css/main.css.scss
  app/javascript/stylesheets/application.scss
  app/views/calculators/calculator.html.slim
Labels: bug, enhancement

#280 Zer 183 results display block values placing mobile version
  app/javascript/css/calculator.css.scss
  app/javascript/css/contact_us.css.scss
  app/javascript/css/main.css.scss
  app/javascript/css/message.css.scss
  app/javascript/stylesheets/application.scss
  app/views/calculators/calculator.html.slim
Labels: bug

#284 Add gem annotate
  Gemfile
  Gemfile.lock
  app/models/app_config.rb
  app/models/calculation.rb
  app/models/calculator.rb
  app/models/feature_flag.rb
  app/models/field.rb
  app/models/message.rb
  app/models/named_value.rb
  app/models/product.rb
  app/models/product_price.rb
  app/models/product_type.rb
  app/models/range_field.rb
  app/models/select.rb
  app/models/user.rb
  app/models/value.rb
  app/serializers/field_serializer.rb
  lib/tasks/auto_annotate_models.rake
  spec/factories/calculations.rb
  spec/factories/calculators.rb
  spec/factories/feature_flags.rb
  spec/factories/fields.rb
  spec/factories/messages.rb
  spec/factories/named_values.rb
  spec/factories/product_types.rb
  spec/factories/products.rb
  spec/factories/range_fields.rb
  spec/factories/selects.rb
  spec/factories/users.rb
  spec/factories/values.rb
  spec/models/app_config_spec.rb
  spec/models/calculation_spec.rb
  spec/models/calculator_spec.rb
  spec/models/feature_flag_spec.rb
  spec/models/field_spec.rb
  spec/models/message_spec.rb
  spec/models/named_value_spec.rb
  spec/models/product_price_spec.rb
  spec/models/product_spec.rb
  spec/models/product_type_spec.rb
  spec/models/range_field_spec.rb
  spec/models/select_spec.rb
  spec/models/user_spec.rb
  spec/models/value_spec.rb
Labels: enhancement

#281 UI correction font words
  app/javascript/css/calculator.css.scss
  app/javascript/css/main.css.scss
  config/locales/en.yml
Labels: enhancement

#291 ZER-186-Fix-the-background-for-mobile-version
  app/javascript/css/main.css.scss
Labels: bug

#285 Zer 171 update product price
  app/controllers/api/v1/diaper_calculators_controller.rb
  app/models/product.rb
  app/models/product_price.rb
  db/migrate/20221111144449_change_category_from_integer_to_string.rb
  db/migrate/20221122164401_change_price_from_float_to_decimal.rb
  db/migrate/20221124165030_add_default_to_category.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/diaper_calculators_spec.rb
  spec/factories/product_price.rb
  spec/factories/product_types.rb
  spec/factories/products.rb
  spec/fixtures/files/app_config.yml
  spec/models/product_price_spec.rb
  spec/support/shared/context/app_config_context.rb
Labels: documentation, enhancement

#293 ZER 147 Add minimum test coverage to CI (CodeCov Integration)
  .circleci/config.yml
  Gemfile.lock
  codecov.yml
  spec/spec_helper.rb
Labels: enhancement

#279 ZER-185 Change text in drop down lists in data input block
  .rubocop.yml
  app/views/calculators/calculator.html.slim
  config/initializers/inflections.rb
  config/locales/en.yml
  config/locales/uk.yml
  lib/inflector_extensions.rb
  spec/lib/inflector_extensions_spec.rb
Labels: enhancement

#276 Zer 157 translate button is named not correctly when user is not logged in
  .rubocop.yml
  app/controllers/admins/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/i18n_extended.rb
  app/controllers/home_controller.rb
  app/controllers/locales_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/users/registrations_controller.rb
  app/helpers/application_helper.rb
  app/helpers/history_helper.rb
  app/jobs/user_report_job.rb
  app/lib/calculation_resolver.rb
  app/mailers/user_mailer.rb
  app/models/authorization.rb
  app/models/user.rb
  app/services/calculators/preferable_service.rb
  app/views/devise/shared/_error_messages.html.slim
  app/views/home/index.html.slim
  app/views/layouts/_admin_navbar.html.slim
  app/views/layouts/_navigation.html.slim
  app/views/layouts/application.html.slim
  bin/spring
  bin/webpack
  bin/webpack-dev-server
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/uat.rb
  config/initializers/sidekiq.rb
  config/initializers/simple_form.rb
  config/initializers/simple_form_bootstrap.rb
  config/locales/devise.en.yml
  config/locales/devise.uk.yml
  config/locales/en.yml
  config/locales/uk.yml
  config/routes.rb
  config/spring.rb
  lib/functions/items_per_month.rb
  spec/features/admin/users_spec.rb
  spec/features/admin_login_spec.rb
  spec/features/reset_password_spec.rb
  spec/features/visit_admin_page_spec.rb
  spec/rails_helper.rb
  spec/requests/home_spec.rb
Labels: bug

#294 Zer 187 stage project on render
  app/javascript/css/calculator.css.scss
  app/javascript/css/main.css.scss
  app/views/calculators/calculator.html.slim
  bin/render-build.sh
Labels: enhancement
