Repository ita-social-projects/ZeroWaste, pull requests merged in 2023-11, with the labels that each got.

#545 feature/revert site settings
  app/assets/stylesheets/pages/feature_flags.scss
  app/controllers/account/site_settings_controller.rb
  app/views/account/site_settings/edit.html.slim
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  config/routes.rb
  spec/factories/site_settings.rb
  spec/requests/site_setting_spec.rb
Labels: enhancement

#549 fix/user_attrbutes_null
  app/controllers/account/users_controller.rb
  app/models/user.rb
  app/views/account/users/index.html.slim
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  db/migrate/20231019194527_change_user_attributes_null.rb
  db/schema.rb
  spec/lib/users_csv_generator_spec.rb
  spec/models/user_spec.rb
  spec/requests/account/users_spec.rb
Labels: bug

#553 feature/upgrade rails
  Gemfile
  Gemfile.lock
  README.md
  config/application.rb
  db/migrate/20210123171144_create_versions.rb
  db/migrate/20210408145903_create_fields.rb
  db/migrate/20210409131859_create_calculators.rb
  db/migrate/20210409171311_create_product_types.rb
  db/migrate/20210409175743_create_products.rb
  db/migrate/20210412104001_add_uuidchecking_to_products.rb
  db/migrate/20210413203204_change_uuid_default_in_fields.rb
  db/migrate/20210413203226_change_uuid_default_in_calculators.rb
  db/migrate/20210413203250_change_uuid_default_in_product_types.rb
  db/migrate/20210413203301_change_uuid_default_in_products.rb
  db/migrate/20210422194341_add_slug_to_calculators.rb
  db/migrate/20210426125453_devise_create_users.rb
  db/migrate/20210426195530_remove_unit_from_fields.rb
  db/migrate/20210426195743_add_unit_to_fields.rb
  db/migrate/20210426201823_change_product_types.rb
  db/migrate/20210428101446_change_products.rb
  db/migrate/20210505150039_add_name_to_users.rb
  db/migrate/20210505150846_add_countries_to_users.rb
  db/migrate/20210510205349_add_last_visit_to_users.rb
  db/migrate/20210513165126_devise_create_admins.rb
  db/migrate/20210524103702_change_calculators.rb
  db/migrate/20210923171630_add_omniauth_to_users.rb
  db/migrate/20211205153832_add_blocked_to_users.rb
  db/migrate/20220103151017_remove_not_null_from_fields_label.rb
  db/migrate/20220107214301_add_fields_to_calculators.rb
  db/migrate/20220122174636_add_contact_form.rb
  db/migrate/20220123171234_add_object_changes_to_versions.rb
  db/migrate/20220427131142_drop_admin.rb
  db/migrate/20220427131337_add_role_to_user.rb
  db/migrate/20220512064155_create_app_config.rb
  db/migrate/20220512070236_init_app_config.rb
  db/migrate/20220728162718_create_product_prices.rb
  db/migrate/20220808110227_create_feature_flags.rb
  db/migrate/20221024174044_fix_calculator_creation.rb
  db/migrate/20221026072654_fix_missed_column_receive_recomndations_to_users.rb
  db/migrate/20221111144449_change_category_from_integer_to_string.rb
  db/migrate/20221122164401_change_price_from_float_to_decimal.rb
  db/migrate/20221124165030_add_default_to_category.rb
  db/migrate/20221210110826_create_prices.rb
  db/migrate/20221210112507_create_categories.rb
  db/migrate/20221210114001_drop_product_prices.rb
  db/migrate/20221210114531_create_join_table_category_categoryables.rb
  db/migrate/20221213215638_add_uniq_index_to_calculators_name.rb
  db/migrate/20221218110600_add_index_for_price.rb
  db/migrate/20221220124102_create_site_settings.rb
  db/migrate/20230215195330_update_diapers_calculator_values_app_config.rb
  db/migrate/20230224135125_add_priority_to_categories.rb
  db/migrate/20230410153510_create_flipper_tables.rb
  db/migrate/20230608072323_add_an_admin_user.rb
  db/migrate/20230710212500_add_default_title_to_site_settings.rb
  db/migrate/20231019194527_change_user_attributes_null.rb
  db/schema.rb
  spec/models/app_config_spec.rb
  spec/models/price_spec.rb
  spec/requests/account/app_configs_spec.rb
Labels: enhancement

#551 fix/minor_improvements
  app/controllers/account/products_controller.rb
  app/views/account/products/edit.html.slim
  app/views/account/products/new.html.slim
  app/views/account/site_settings/edit.html.slim
Labels: bug

#546 feature/uniquness_for_product
  app/models/product.rb
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  db/migrate/20230917082603_add_index_to_product.rb
  db/schema.rb
  spec/models/product_spec.rb
  spec/requests/products_spec.rb
Labels: Improvement

#560 closes #558 fix wrong error message
  app/models/site_setting.rb
  spec/models/site_setting_spec.rb
Labels: bug

#577 fix/remove_useless_files_&_fix_flash
  Gemfile
  Gemfile.lock
  app/javascript/application.js
  app/javascript/channels/index.js
  app/javascript/controllers/application.js
  app/views/account/calculators/fields/_calculation.html.slim
  app/views/account/calculators/fields/_form.html.slim
  app/views/account/calculators/fields/_named_value.html.slim
  app/views/account/calculators/fields/_new.html.slim
  app/views/account/calculators/fields/_range_value.html.slim
  app/views/account/calculators/fields/_select.html.slim
  app/views/account/calculators/fields/_value.html.slim
  app/views/account/calculators/fields/new.js.erb
  config/importmap.rb
  config/initializers/devise.rb
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/staging.js
  config/webpack/test.js
  config/webpack/uat.js
Labels: bug

#576 #570--Products-page]-The-product-page-opens-after-clicking-on-the-"Delete"-button
  app/views/account/products/index.html.slim
  app/views/account/products/show.html.slim
Labels: bug, Priority: medium

#574 Site Settings rouring error
  config/routes.rb
Labels: bug
