Repository ita-social-projects/ZeroWaste, pull requests merged in 2023-08, with the labels that each got.

#523 change of order
  app/views/layouts/_account_navbar.html.slim
Labels: bug

#536 feature/533_site_settings_design
  app/assets/stylesheets/pages/feature_flags.scss
  app/assets/stylesheets/pages/main.scss
  app/views/account/site_settings/edit.html.slim
  config/locales/en/en.yml
  config/locales/uk/uk.yml
Labels: enhancement

#481 CRUD methods for users on admin side
  app/controllers/account/users_controller.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/account/users/index.html.slim
  app/views/account/users/new.html.erb
  app/views/user_mailer/welcome_email.html.erb
  app/views/user_mailer/welcome_email.text.erb
  config/environments/test.rb
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  config/routes.rb
  spec/features/account/users_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/requests/account/users_spec.rb
Labels: Story

#509 Move tests lib specs from models folder to libs folder
  spec/lib/calculation_resolver_spec.rb
  spec/lib/calculator_resolver_spec.rb
  spec/lib/users_csv_generator_spec.rb
  spec/models/feature_flag_spec.rb
Labels: Improvement

#538 fix/duplicate_seeds
  db/seeds.rb
Labels: bug
