Repository ita-social-projects/ZeroWaste, pull requests merged in 2023-07, with the labels that each got.

#406 added default value to site settings
  db/migrate/20230710212500_add_default_title_to_site_settings.rb
  db/schema.rb
Labels: Improvement

#466 fix/update develop CI
  .circleci/config.yml
  .github/workflows/ci.yml
  bin/circleci_db_setup
  spec/features/account/create_calculator_spec.rb
  spec/features/navigator_spec.rb
  spec/features/product_category_spec.rb
  spec/features/visit_calculator_spec.rb
  spec/models/category_categoryable_spec.rb
  spec/models/product_spec.rb
  spec/requests/calculators_spec.rb
  spec/requests/diaper_calculators_spec.rb
  spec/requests/feature_flags_spec.rb
Labels: enhancement

#524 Fix/seeds
  db/seeds.rb
Labels: bug

#526 Validation and verification field length and formation for "Name" in "Categories"
  app/models/category.rb
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  db/seeds.rb
  spec/models/category_spec.rb
Labels: bug

#502 fix/pending tests
  app/decorators/calculator_decorator.rb
  app/models/calculator.rb
  app/models/category.rb
  app/models/category_categoryable.rb
  app/models/price.rb
  app/models/site_setting.rb
  app/views/account/calculators/new.html.slim
  app/views/account/shared/_navigation.html.slim
  config/locales/en/en.yml
  spec/factories/app_configs.rb
  spec/factories/calculators.rb
  spec/factories/categories.rb
  spec/factories/feature_flags.rb
  spec/factories/prices.rb
  spec/factories/site_settings.rb
  spec/features/account/create_calculator_spec.rb
  spec/features/admin_login_spec.rb
  spec/features/navigator_spec.rb
  spec/features/product_category_spec.rb
  spec/features/visit_calculator_spec.rb
  spec/fixtures/app_configs.yml
  spec/models/calculator_spec.rb
  spec/models/category_categoryable_spec.rb
  spec/models/category_spec.rb
  spec/models/price_spec.rb
  spec/models/product_spec.rb
  spec/models/site_setting_spec.rb
  spec/rails_helper.rb
  spec/requests/calculators_spec.rb
  spec/requests/diaper_calculators_spec.rb
  spec/requests/feature_flags_spec.rb
  spec/support/shared/context/feature_flags.rb
  spec/views/calculators/calculator.html.slim_spec.rb
Labels: bug, Priority: medium
