Repository ita-social-projects/ZeroWaste, pull requests merged in 2024-11, with the labels that each got.

#924 910 Created menstrual hygiene products calculator
  .rubocop.yml
  app/assets/images/pad_scales.png
  app/assets/images/pads_bought.png
  app/assets/images/pads_to_buy.png
  app/controllers/api/v1/pad_calculators_controller.rb
  app/controllers/calculators_controller.rb
  app/helpers/calculators_helper.rb
  app/javascript/controllers/mhc_calculator_controller.js
  app/javascript/controllers/pad_results_controller.js
  app/services/calculators/pad_usage_service.rb
  app/validators/mhc_calculator_validator.rb
  app/views/calculators/mhc_calculator.erb
  app/views/layouts/_mhc_description_block.html.erb
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  config/routes.rb
  spec/features/account/users_spec.rb
  spec/requests/calculators_spec.rb
  spec/requests/pad_calculators_spec.rb
  spec/services/calculators/pad_usage_service_spec.rb
  spec/support/shared/presence_validation_example.rb
  spec/validators/mhc_calculator_validator_spec.rb
Labels: enhancement, Priority: high

#954 #866-fix refreshing new Category page
  app/views/account/categories/new.html.erb
  app/views/account/categories/new.turbo_stream.erb
  app/views/account/categories/partials/new/_form.html.erb
Labels: bug, Functional

#969 Added flipper, so admin could enable or disable mhc calculator
  app/controllers/calculators_controller.rb
  app/views/account/shared/_navigation.html.erb
  config/initializers/flipper/features.rb
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  spec/requests/calculators_spec.rb
  spec/support/shared/context/feature_flags.rb
Labels: enhancement

#983 Added feature flipper for calculators constructor
  app/controllers/account/calculators_controller.rb
  app/controllers/calculators_controller.rb
  app/views/account/shared/_navigation.html.erb
  app/views/layouts/_account_navbar.html.erb
  config/initializers/flipper/features.rb
  config/locales/en/en.yml
  config/locales/uk/uk.yml
  spec/features/account/calculators_spec.rb
  spec/features/navigator_spec.rb
  spec/features/show_calculator_spec.rb
  spec/features/visit_login_spec.rb
  spec/requests/account/calculators_spec.rb
  spec/requests/calculators_spec.rb
  spec/support/shared/context/feature_flags.rb
Labels: enhancement
